### ISSUE TITLE
Getting the following error while debugging 

### ISSUE THREAD

**Issue by viveksingh17** [OfficeDev/Word-Add-in-ClauseLibrary-Code-Sample#3]
![image](https://user-images.githubusercontent.com/29349918/29740647-0c42ef7a-8a79-11e7-8a64-fe6c589fc6ba.png)

**Comment by soonwong** [comment]
Have you ensured that all nuget packages are downloaded?

**Comment by viveksingh17** [comment]
@soonwong  yes all the nuget packages are downloaded

**Comment by lindalu-MSFT** [comment]
Closing all issues since this repo is being archived and no longer maintained.
